# Generated by Django 4.2 on 2023-06-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteritem',
            name='IsActive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
