# Generated by Django 4.2 on 2023-07-06 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproverMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_approver', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_approver', models.CharField(blank=True, max_length=100, null=True)),
                ('sequence', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'ApproverMatrix',
                'db_table': 'ApproverMatrix',
            },
        ),
        migrations.CreateModel(
            name='MasterRole',
            fields=[
                ('roleId', models.AutoField(primary_key=True, serialize=False)),
                ('rolename', models.CharField(blank=True, max_length=100, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'MasterRole',
                'db_table': 'MasterRole',
            },
        ),
        migrations.CreateModel(
            name='ModuleMaster',
            fields=[
                ('moduleId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('module_name', models.CharField(max_length=100, null=True)),
                ('module_slug', models.SlugField(max_length=100, null=True)),
                ('root', models.CharField(max_length=100, null=True)),
                ('m_color', models.CharField(max_length=100, null=True)),
                ('m_icon_name', models.CharField(max_length=100, null=True)),
                ('m_link', models.CharField(max_length=100, null=True)),
                ('menu_flag', models.BooleanField(default=True)),
                ('sort_no', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ModuleMaster',
                'db_table': 'ModuleMaster',
            },
        ),
        migrations.CreateModel(
            name='ModuleAccess',
            fields=[
                ('moduleAccessId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('is_approver', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_dsin', models.BooleanField(default=False)),
                ('is_requester', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('moduleId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='approval.modulemaster')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ModuleAccess',
                'db_table': 'ModuleAccess',
            },
        ),
        migrations.CreateModel(
            name='MasterRoleMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employeeId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('roleId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='approval.masterrole')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'MasterRoleMapping',
                'db_table': 'MasterRoleMapping',
            },
        ),
        migrations.CreateModel(
            name='ApprovalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approvalUserName', models.CharField(blank=True, max_length=100, null=True)),
                ('approverEmail', models.EmailField(blank=True, max_length=100, null=True)),
                ('sequence', models.IntegerField(blank=True, default=0, null=True)),
                ('approverType', models.CharField(blank=True, choices=[('BuHead', 'BuHead'), ('DSINHead', 'DSINHead'), ('FinanceHead', 'FinanceHead'), ('MD', 'MD'), ('DSINMPR', 'DSINMPR')], max_length=100, null=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('approvaldatetime', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procurementId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.masterprocurement')),
            ],
            options={
                'verbose_name_plural': 'ApprovalTransaction',
                'db_table': 'ApprovalTransaction',
                'ordering': ['id'],
            },
        ),
    ]
