# Generated by Django 4.2 on 2023-06-08 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproverMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_approver', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_approver', models.CharField(blank=True, max_length=100, null=True)),
                ('sequence', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'ApproverMatrix',
                'db_table': 'ApproverMatrix',
            },
        ),
        migrations.CreateModel(
            name='AppTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(blank=True, default=0, null=True)),
                ('approverEmail', models.EmailField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('approvaldatetime', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_by', to=settings.AUTH_USER_MODEL)),
                ('procurementId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.masterprocurement')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AppTransaction',
                'db_table': 'AppTransaction',
            },
        ),
    ]
