# Generated by Django 4.2 on 2023-06-15 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0001_initial'),
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaltransaction',
            name='procurementId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.masterprocurement'),
        ),
    ]
