# Generated by Django 4.2 on 2023-06-09 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0001_initial'),
        ('approval', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaltransaction',
            name='procurementId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.masterprocurement'),
        ),
        migrations.AddField(
            model_name='approvaltransaction',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
