# Generated by Django 4.2 on 2023-06-09 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvaltransaction',
            options={'verbose_name_plural': 'ApprovalTransaction'},
        ),
        migrations.AlterModelTable(
            name='approvaltransaction',
            table='ApprovalTransaction',
        ),
    ]
