# Generated by Django 4.2 on 2023-06-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterprocurement',
            name='File',
            field=models.ImageField(blank=True, null=True, upload_to='procurement/'),
        ),
    ]
