# Generated by Django 4.2 on 2023-06-22 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='procurement/%Y/%m/%d/%H_%M_%S')),
                ('filetype', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Attachments',
                'db_table': 'Attachments',
            },
        ),
        migrations.RemoveField(
            model_name='inlineitem',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='masterprocurement',
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='MasterUpload',
        ),
        migrations.AddField(
            model_name='attachments',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='procurement.masterprocurement'),
        ),
    ]
