# Generated by Django 4.2 on 2023-07-10 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_masterprocurement_totalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inlineitem',
            name='procurement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inlineitem', to='procurement.masterprocurement'),
            preserve_default=False,
        ),
    ]
