# Generated by Django 4.2 on 2023-06-26 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inlineitem',
            name='procurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inlineitem', to='procurement.masterprocurement'),
        ),
    ]
