# Generated by Django 4.2 on 2023-07-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_alter_inlineitem_procurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterprocurement',
            name='TotalAmount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
