# Generated by Django 4.2 on 2023-07-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_alter_masterprocurement_totalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inlineitem',
            name='costcenter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
