# Generated by Django 4.2 on 2023-07-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_alter_inlineitem_costcenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterprocurement',
            name='PurchaseDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
