# Generated by Django 4.2 on 2023-07-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_alter_masterprocurement_purchasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterprocurement',
            name='Age',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
